name: Deploy

on:
  push:
    branches:
      - main

jobs:
  checkout-DeployHeroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKUKEY}}
          heroku_app_name: ${{secrets.HEROKUAPPNAME}}
          heroku_email: ${{secrets.HEROKUEMAIL}}
